databases:
  main:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306?serverTimezone=UTC&characterEncoding=UTF-8
    username: sample
    password: ass

spring:
  datasource:
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    defer-datasource-initialization: false
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: never